name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull sangasangasanga/swe5006:latest
    - name: Delete Old docker container
      run: sudo docker rm -f swe5006-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name swe5006-container sangasangasanga/swe5006