# name: CICD

# on:
#   push:
#     branches: [master]

# jobs:
#   build:
#     runs-on: [ubuntu-latest]
#     steps:
#       - name: Checkout source
#         uses: actions/checkout@v3
#       - name: Setup Java
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'temurin'
#           java-version: '17'
#       - name: Build Project
#         # working-directory: /home/runner/work/swe5006-aws-ec2/swe5006-aws-ec2/beautyApp/backend
#         run: mvn clean package -DskipTests
#       - name: Login to docker hub
#         run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
#       - name: Build docker image
#         run: docker build -t sangasangasanga/swe5006-aws-ec2 .
#       - name: Publish image to docker hub
#         run: docker push sangasangasanga/swe5006-aws-ec2:latest

#   deploy:
#     needs: build
#     runs-on: [swe5006-aws-ec2]
#     steps:
#       - name: Pull Image from docker hub
#         run: sudo docker pull sangasangasanga/swe5006-aws-ec2:latest
#       - name: Delete old container
#         run: sudo docker rm -f deploy-container || true
#       - name: Run docker container
#         run: sudo docker run -d -p 8080:8080 --name deploy-container sangasangasanga/swe5006-aws-ec2


name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout source code
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '17'

      # Build Backend Project
      - name: Build Backend Project
        working-directory: ./beautyApp/backend
        run: mvn clean package -DskipTests

      # Build Frontend Docker Image
      - name: Build Frontend Docker Image
        working-directory: ./beautyApp/frontend
        run: |
          docker build -t sangasangasanga/ec2-frontend:latest -f Dockerfile .
      
      # Build Backend Docker Image
      - name: Build Backend Docker Image
        working-directory: ./beautyApp/backend
        run: |
          docker build -t sangasangasanga/ec2-backend:latest -f Dockerfile .
      
      # Login to Docker Hub
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Push Frontend Docker Image
      - name: Push Frontend Docker Image
        run: docker push sangasangasanga/ec2-frontend:latest
      
      # Push Backend Docker Image
      - name: Push Backend Docker Image
        run: docker push sangasangasanga/ec2-backend:latest

  deploy-frontend:
    needs: build
    runs-on: frontend # specify the name or label of your frontend EC2 instance runner
    steps:
      # Pull Frontend Docker Image
      - name: Pull Frontend Docker Image
        run: |
          docker system prune -f
          docker pull sangasangasanga/ec2-frontend:latest
      
      # Remove existing Frontend container
      - name: Remove existing Frontend container
        run: docker rm -f frontend-container || true
      
      # Deploy Frontend
      - name: Deploy Frontend
        run: docker run -d -p 3000:3000 --name frontend-container sangasangasanga/ec2-frontend:latest
      
  deploy-backend:
    needs: build
    runs-on: backend # specify the name or label of your backend EC2 instance runner
    steps:
      # Pull Backend Docker Image
      - name: Pull Backend Docker Image
        run: docker pull sangasangasanga/ec2-backend:latest
      
      # Remove existing Backend container
      - name: Remove existing Backend container
        run: docker rm -f backend-container || true
      
      # Deploy Backend
      - name: Deploy Backend
        run: docker run -d -p 8080:8080 --name backend-container sangasangasanga/ec2-backend:latest
